# Generated by Django 6.1.1 on 2026-10-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_title_product_name_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
