services:
  web:
    build:
      context: .
    ports:
      - mode: ingress
        target: 8000
        published: 8000
    environment:
      SECRET_KEY:
      DEBUG: "False"
    deploy:
      resources:
        reservations:
          memory: 512M
